### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Charlie-robin** [adampaulsackfield/fd-portfolio#22]
# Feedback

## Requirements:

1. A deployed website (using GitHub Pages) : DONE
2. A public GitHub repository for your codebase : DONE
3. Use HTML & SCSS : DONE
4. Make good use of semantic HTML elements : DONE
5. Be responsive (mobile-first) and built with accessibility in mind : DONE
6. Code is highly readable (good naming and indented correctly) : DONE

## Score

[MARKING-SCHEME](https://github.com/nology-tech/Augusta-Course-Resources/blob/main/student-resources/00-slides/01-web/marking-scheme.md)

| Category             | Score    |
| -------------------- | -------- |
| Site Output          | 40 / 50  |
| Responsiveness       | 15 / 15  |
| Code Knowledge & Use | 15 / 20  |
| Readability          | 10 / 15  |
| Version Control      | 10 / 10  |
| Total Score          | 90 / 110 |

### Positive

Your project is great! it has clearly been a good exercise for you to build a website from a wire-frame.

I am glad you pushed yourself by choosing the advanced design with multiple breakpoints. Keep challenging yourself!

You have extended and customized the project which is also great please keep this up!

Your JS feature is great and works seamlessly. Good job researching animations and bringing them into the mix :).

```js
		if (entry.isIntersecting) {
			entry.target.classList.add('show');
		} else entry.target.classList.remove('show');

    // I WONDER IF ^^ COULD JUST BE TOGGLE?
    entry.target.classList.toggle('show)
```

You demonstrating a solid understanding of the majority of topics we have covered so far, keep it up and keep on using BEM, SCSS, grid and flex.

### Constructive

There are couple of things I think you can tidy up in your project.

The majority of it is great but it is good to have things to work on.

- I wouldn't use the `<i></i>` tag for your icons. The Font awesome docs do tell you two, they have taken the [italic tag](https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_i) and kind of stole it. The classes do the styling so you should be able to use a `<span>` or `<div>`.
- You have 32 `<h1>'s`, you should only have one [w3](https://www.w3schools.com/tags/tag_hn.asp), this would be for the main title of the page.
- Your BEM is a bit hit and miss which is fine as it takes practice.
  - You want avoid using any html css selectors, the rule is everything that is going to have specific styles needs a class name. Resets are the exception.
  - You generally don't nest it as you have. You would have block > element > modifier and that is it. The example below has block > element > h1 > span.

```scss
.home {
  display: grid;
  grid-template-columns: repeat(11, 1fr);
  padding: 0 2rem;

  &__details {
    grid-column: span 12;
    grid-row: 2;

    h1 {
      font-size: 2.5rem;

      span {
        color: $accent;
      }
    }

    p {
      padding: 1.5rem 0;
      color: $text-grey-dark;
      font-weight: 300;
    }
    // OTHER STYLES HERE
  }
}

// THE STYLES ABOVE WOULD PROBABLY BE

.home {
  display: grid;
  grid-template-columns: repeat(11, 1fr);
  padding: 0 2rem;

  &__details {
    grid-column: span 12;
    grid-row: 2;
  }

  &__title {
    font-size: 2.5rem;
  }

  &__accent {
    color: $accent;

    // EXAMPLE WITH A MODIFIER
    &--example {
      color: red;
    }
  }

  &__text {
    padding: 1.5rem 0;
    color: $text-grey-dark;
    font-weight: 300;
  }
  // OTHER STYLES HERE
}
```

- You have a slight side scroll which can be fixed, I think it is being caused by the `body::before`. You should be able to stop it by using `overflow-x`.

```scss
body {
  overflow-x: hidden;
}
```

Try and carry the feedback over to your next project. Any questions let me know.

---
